### ISSUE TITLE
linux-odroid.install sha512sum doesn't match

### ISSUE THREAD

**Issue by frol** [ztombol/odroid-tools#1]
On my fresh git clone, `linux-odroid.install` has `659c0b78398dc59a1d04b604780f3fa83018a3193f59daba84f2b10d981c096e0ac8c24a746288bd08a6cfb54a1c5c67f956ca0fb7f9b98809f307d7df3385a5` sha512sum, but another one is listed in the PKGBUILD.

I have just patched it, so it is not critical. I am moving forward trying to finally build it.

**Comment by ztombol** [comment]
Looks like I forgot to update the checksums. Thanks!
